server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 301 https://35-196-65-232.sslip.io$request_uri;
}

server {
    listen 443 ssl default_server;
    server_name _;
    ssl_certificate /etc/letsencrypt/live/35-196-65-232.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/35-196-65-232.sslip.io/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
